// Code generated by protoc-gen-go.
// source: protos/toplist/toplist.proto
// DO NOT EDIT!

/*
Package video is a generated protocol buffer package.

It is generated from these files:
	protos/toplist/toplist.proto

It has these top-level messages:
	RequestModifyList
	RequestGetList
	ResponseGetList
	ResponseGeneral
	KeyObj
*/
package video

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopType int32

const (
	TopType_like          TopType = 0
	TopType_hot           TopType = 1
	TopType_view          TopType = 2
	TopType_trend         TopType = 3
	TopType_time          TopType = 4
	TopType_feature       TopType = 5
	TopType_upload        TopType = 6
	TopType_video_created TopType = 7
)

var TopType_name = map[int32]string{
	0: "like",
	1: "hot",
	2: "view",
	3: "trend",
	4: "time",
	5: "feature",
	6: "upload",
	7: "video_created",
}
var TopType_value = map[string]int32{
	"like":          0,
	"hot":           1,
	"view":          2,
	"trend":         3,
	"time":          4,
	"feature":       5,
	"upload":        6,
	"video_created": 7,
}

func (x TopType) String() string {
	return proto.EnumName(TopType_name, int32(x))
}
func (TopType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TopTime int32

const (
	TopTime_today TopTime = 0
	TopTime_total TopTime = 1
	TopTime_month TopTime = 2
)

var TopTime_name = map[int32]string{
	0: "today",
	1: "total",
	2: "month",
}
var TopTime_value = map[string]int32{
	"today": 0,
	"total": 1,
	"month": 2,
}

func (x TopTime) String() string {
	return proto.EnumName(TopTime_name, int32(x))
}
func (TopTime) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TopKey int32

const (
	TopKey_top_video       TopKey = 0
	TopKey_time_in_top_100 TopKey = 1
	TopKey_top_hashtag     TopKey = 2
	TopKey_follow_video    TopKey = 3
	TopKey_favorite_video  TopKey = 4
	TopKey_video_of_audio  TopKey = 5
	TopKey_audio_uploaded  TopKey = 6
	TopKey_top_user        TopKey = 7
	TopKey_top_daily_1x    TopKey = 8
	TopKey_top_daily_2x    TopKey = 9
	TopKey_top_xfactor     TopKey = 10
)

var TopKey_name = map[int32]string{
	0:  "top_video",
	1:  "time_in_top_100",
	2:  "top_hashtag",
	3:  "follow_video",
	4:  "favorite_video",
	5:  "video_of_audio",
	6:  "audio_uploaded",
	7:  "top_user",
	8:  "top_daily_1x",
	9:  "top_daily_2x",
	10: "top_xfactor",
}
var TopKey_value = map[string]int32{
	"top_video":       0,
	"time_in_top_100": 1,
	"top_hashtag":     2,
	"follow_video":    3,
	"favorite_video":  4,
	"video_of_audio":  5,
	"audio_uploaded":  6,
	"top_user":        7,
	"top_daily_1x":    8,
	"top_daily_2x":    9,
	"top_xfactor":     10,
}

func (x TopKey) String() string {
	return proto.EnumName(TopKey_name, int32(x))
}
func (TopKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ErrorCode int32

const (
	ErrorCode_NOT_OK ErrorCode = 0
	ErrorCode_OK     ErrorCode = 200
	// client
	ErrorCode_REQUEST_INVALID ErrorCode = 1000
	// server response
	ErrorCode_VIDEOID_WRONG   ErrorCode = 1100
	ErrorCode_VIDEO_NOT_EXIST ErrorCode = 1101
	// server - Generic error for client
	ErrorCode_DB_ERROR     ErrorCode = 2000
	ErrorCode_DATA_ERROR   ErrorCode = 2001
	ErrorCode_SERVER_ERROR ErrorCode = 2002
	// general - unknown
	ErrorCode_UNKNOWN       ErrorCode = 3000
	ErrorCode_NETWORK_ERROR ErrorCode = 3001
	ErrorCode_SYSTEM_ERROR  ErrorCode = 3002
)

var ErrorCode_name = map[int32]string{
	0:    "NOT_OK",
	200:  "OK",
	1000: "REQUEST_INVALID",
	1100: "VIDEOID_WRONG",
	1101: "VIDEO_NOT_EXIST",
	2000: "DB_ERROR",
	2001: "DATA_ERROR",
	2002: "SERVER_ERROR",
	3000: "UNKNOWN",
	3001: "NETWORK_ERROR",
	3002: "SYSTEM_ERROR",
}
var ErrorCode_value = map[string]int32{
	"NOT_OK":          0,
	"OK":              200,
	"REQUEST_INVALID": 1000,
	"VIDEOID_WRONG":   1100,
	"VIDEO_NOT_EXIST": 1101,
	"DB_ERROR":        2000,
	"DATA_ERROR":      2001,
	"SERVER_ERROR":    2002,
	"UNKNOWN":         3000,
	"NETWORK_ERROR":   3001,
	"SYSTEM_ERROR":    3002,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RequestModifyList struct {
	Member string  `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
	Score  string  `protobuf:"bytes,2,opt,name=score" json:"score,omitempty"`
	Key    *KeyObj `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *RequestModifyList) Reset()                    { *m = RequestModifyList{} }
func (m *RequestModifyList) String() string            { return proto.CompactTextString(m) }
func (*RequestModifyList) ProtoMessage()               {}
func (*RequestModifyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestModifyList) GetKey() *KeyObj {
	if m != nil {
		return m.Key
	}
	return nil
}

type RequestGetList struct {
	Key *KeyObj `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *RequestGetList) Reset()                    { *m = RequestGetList{} }
func (m *RequestGetList) String() string            { return proto.CompactTextString(m) }
func (*RequestGetList) ProtoMessage()               {}
func (*RequestGetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestGetList) GetKey() *KeyObj {
	if m != nil {
		return m.Key
	}
	return nil
}

type ResponseGetList struct {
	Error       ErrorCode         `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Detail      map[string]string `protobuf:"bytes,3,rep,name=detail" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResponseGetList) Reset()                    { *m = ResponseGetList{} }
func (m *ResponseGetList) String() string            { return proto.CompactTextString(m) }
func (*ResponseGetList) ProtoMessage()               {}
func (*ResponseGetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResponseGetList) GetDetail() map[string]string {
	if m != nil {
		return m.Detail
	}
	return nil
}

type ResponseGeneral struct {
	Error       ErrorCode `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *ResponseGeneral) Reset()                    { *m = ResponseGeneral{} }
func (m *ResponseGeneral) String() string            { return proto.CompactTextString(m) }
func (*ResponseGeneral) ProtoMessage()               {}
func (*ResponseGeneral) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type KeyObj struct {
	Key  TopKey  `protobuf:"varint,1,opt,name=key,enum=video.TopKey" json:"key,omitempty"`
	Kind TopType `protobuf:"varint,2,opt,name=kind,enum=video.TopType" json:"kind,omitempty"`
	Time TopTime `protobuf:"varint,3,opt,name=time,enum=video.TopTime" json:"time,omitempty"`
}

func (m *KeyObj) Reset()                    { *m = KeyObj{} }
func (m *KeyObj) String() string            { return proto.CompactTextString(m) }
func (*KeyObj) ProtoMessage()               {}
func (*KeyObj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*RequestModifyList)(nil), "video.RequestModifyList")
	proto.RegisterType((*RequestGetList)(nil), "video.RequestGetList")
	proto.RegisterType((*ResponseGetList)(nil), "video.ResponseGetList")
	proto.RegisterType((*ResponseGeneral)(nil), "video.ResponseGeneral")
	proto.RegisterType((*KeyObj)(nil), "video.KeyObj")
	proto.RegisterEnum("video.TopType", TopType_name, TopType_value)
	proto.RegisterEnum("video.TopTime", TopTime_name, TopTime_value)
	proto.RegisterEnum("video.TopKey", TopKey_name, TopKey_value)
	proto.RegisterEnum("video.ErrorCode", ErrorCode_name, ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TopListService service

type TopListServiceClient interface {
	GetList(ctx context.Context, in *RequestGetList, opts ...grpc.CallOption) (*ResponseGetList, error)
	AddList(ctx context.Context, in *RequestModifyList, opts ...grpc.CallOption) (*ResponseGeneral, error)
	RemoveList(ctx context.Context, in *RequestModifyList, opts ...grpc.CallOption) (*ResponseGeneral, error)
}

type topListServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopListServiceClient(cc *grpc.ClientConn) TopListServiceClient {
	return &topListServiceClient{cc}
}

func (c *topListServiceClient) GetList(ctx context.Context, in *RequestGetList, opts ...grpc.CallOption) (*ResponseGetList, error) {
	out := new(ResponseGetList)
	err := grpc.Invoke(ctx, "/video.TopListService/GetList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topListServiceClient) AddList(ctx context.Context, in *RequestModifyList, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.TopListService/AddList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topListServiceClient) RemoveList(ctx context.Context, in *RequestModifyList, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.TopListService/RemoveList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TopListService service

type TopListServiceServer interface {
	GetList(context.Context, *RequestGetList) (*ResponseGetList, error)
	AddList(context.Context, *RequestModifyList) (*ResponseGeneral, error)
	RemoveList(context.Context, *RequestModifyList) (*ResponseGeneral, error)
}

func RegisterTopListServiceServer(s *grpc.Server, srv TopListServiceServer) {
	s.RegisterService(&_TopListService_serviceDesc, srv)
}

func _TopListService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopListServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.TopListService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopListServiceServer).GetList(ctx, req.(*RequestGetList))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopListService_AddList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopListServiceServer).AddList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.TopListService/AddList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopListServiceServer).AddList(ctx, req.(*RequestModifyList))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopListService_RemoveList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopListServiceServer).RemoveList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.TopListService/RemoveList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopListServiceServer).RemoveList(ctx, req.(*RequestModifyList))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.TopListService",
	HandlerType: (*TopListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _TopListService_GetList_Handler,
		},
		{
			MethodName: "AddList",
			Handler:    _TopListService_AddList_Handler,
		},
		{
			MethodName: "RemoveList",
			Handler:    _TopListService_RemoveList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/toplist/toplist.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xce, 0xd8, 0xb1, 0xc7, 0x2e, 0xc7, 0x76, 0xa7, 0x97, 0x25, 0x96, 0x15, 0x44, 0x64, 0x2e,
	0x91, 0x05, 0xf1, 0xc6, 0x5c, 0x50, 0x6e, 0x01, 0x8f, 0x22, 0xcb, 0xbb, 0x1e, 0x31, 0x9e, 0x4d,
	0x00, 0x09, 0x0d, 0x1d, 0x4f, 0xd9, 0x69, 0x32, 0x9e, 0x1e, 0x7a, 0xda, 0xde, 0xf8, 0xca, 0x2b,
	0xf0, 0x16, 0x9c, 0x38, 0x02, 0x4f, 0xb0, 0x07, 0x40, 0xfc, 0xbc, 0x02, 0x07, 0x1e, 0x03, 0x75,
	0x7b, 0x9c, 0x38, 0x10, 0xed, 0x21, 0xa7, 0xe9, 0xfa, 0xfa, 0xab, 0xef, 0xab, 0xaa, 0x51, 0x35,
	0xec, 0x27, 0x52, 0x28, 0x91, 0x76, 0x94, 0x48, 0x22, 0x9e, 0xaa, 0xf5, 0xf7, 0xc8, 0xc0, 0xb4,
	0xb0, 0xe0, 0x21, 0x8a, 0xe6, 0xfe, 0x54, 0x88, 0x69, 0x84, 0x1d, 0x96, 0xf0, 0x0e, 0x8b, 0x63,
	0xa1, 0x98, 0xe2, 0x22, 0x4e, 0x57, 0xa4, 0xd6, 0x10, 0x76, 0x3d, 0xfc, 0x66, 0x8e, 0xa9, 0x7a,
	0x21, 0x42, 0x3e, 0x59, 0x3e, 0xe7, 0xa9, 0xa2, 0x35, 0x28, 0xce, 0x70, 0x76, 0x89, 0xb2, 0x61,
	0x1d, 0x58, 0x87, 0x65, 0x5a, 0x85, 0x42, 0x3a, 0x16, 0x12, 0x1b, 0x39, 0x13, 0x36, 0x21, 0x7f,
	0x8d, 0xcb, 0x46, 0xfe, 0xc0, 0x3a, 0xac, 0x74, 0xab, 0x47, 0xc6, 0xe6, 0x68, 0x80, 0x4b, 0xf7,
	0xf2, 0xeb, 0xd6, 0xfb, 0x50, 0xcb, 0xf4, 0xce, 0x50, 0x19, 0xb1, 0x8c, 0x6d, 0x3d, 0xc4, 0xfe,
	0xde, 0x82, 0xba, 0x87, 0x69, 0x22, 0xe2, 0x14, 0xd7, 0xfc, 0x77, 0xa1, 0x80, 0x52, 0x8a, 0x95,
	0x77, 0xad, 0x4b, 0xb2, 0x0c, 0x47, 0x63, 0x9f, 0x88, 0x10, 0xe9, 0x13, 0xa8, 0x84, 0x98, 0x8e,
	0x25, 0x4f, 0x74, 0x23, 0x59, 0x4d, 0x5d, 0x28, 0x86, 0xa8, 0x18, 0x8f, 0x1a, 0xf9, 0x83, 0xfc,
	0x61, 0xa5, 0xdb, 0xca, 0xd2, 0xfe, 0xa3, 0x7e, 0xd4, 0x33, 0x24, 0x27, 0x56, 0x72, 0xd9, 0xfc,
	0x00, 0x2a, 0x1b, 0x21, 0xad, 0xdc, 0x15, 0x6a, 0x5a, 0x5e, 0xb0, 0x68, 0x9e, 0xb5, 0x7c, 0x92,
	0xfb, 0xc8, 0x6a, 0x9d, 0x6d, 0xd6, 0x1a, 0xa3, 0x64, 0xd1, 0xe3, 0x6a, 0x6d, 0x7d, 0x05, 0xc5,
	0x55, 0xff, 0x9b, 0xb3, 0xa9, 0xdd, 0xce, 0xc6, 0x17, 0xc9, 0x00, 0x97, 0x74, 0x1f, 0xb6, 0xaf,
	0x79, 0x1c, 0x9a, 0x9c, 0x5a, 0xb7, 0x76, 0x77, 0xe9, 0x2f, 0x13, 0xd4, 0xb7, 0x8a, 0xcf, 0xd0,
	0xfc, 0x84, 0xfb, 0xb7, 0x7c, 0x86, 0xed, 0x29, 0xd8, 0x6b, 0x62, 0x09, 0xb6, 0x23, 0x7e, 0x8d,
	0x64, 0x8b, 0xda, 0x90, 0xbf, 0x12, 0x8a, 0x58, 0x1a, 0x5a, 0x70, 0x7c, 0x45, 0x72, 0xb4, 0x0c,
	0x05, 0x25, 0x31, 0x0e, 0x49, 0x5e, 0x83, 0x5a, 0x90, 0x6c, 0xd3, 0x0a, 0xd8, 0x13, 0x64, 0x6a,
	0x2e, 0x91, 0x14, 0x28, 0x40, 0x71, 0x9e, 0x44, 0x82, 0x85, 0xa4, 0x48, 0x77, 0xa1, 0x6a, 0x6c,
	0x82, 0xb1, 0x44, 0xa6, 0x30, 0x24, 0x76, 0xbb, 0xbd, 0x32, 0xe2, 0x33, 0x34, 0x5a, 0x22, 0x64,
	0x4b, 0xb2, 0xb5, 0x3a, 0x2a, 0x16, 0x11, 0x4b, 0x1f, 0x67, 0x22, 0x56, 0x57, 0x24, 0xd7, 0xfe,
	0xcd, 0x82, 0x62, 0xd6, 0x5b, 0x15, 0xca, 0x4a, 0x24, 0x81, 0x51, 0x23, 0x5b, 0xf4, 0x09, 0xd4,
	0xb5, 0x77, 0xc0, 0xe3, 0x40, 0xc3, 0xc7, 0xcf, 0x9e, 0x11, 0x8b, 0xd6, 0xa1, 0xa2, 0x83, 0x2b,
	0x96, 0x5e, 0x29, 0x36, 0x25, 0x39, 0x4a, 0x60, 0x67, 0x22, 0xa2, 0x48, 0xbc, 0xca, 0xf2, 0xf2,
	0x94, 0x42, 0x6d, 0xc2, 0x16, 0x42, 0x72, 0x85, 0x19, 0xb6, 0xad, 0xb1, 0x55, 0x91, 0x62, 0x12,
	0xb0, 0x79, 0xc8, 0x05, 0x29, 0x68, 0xcc, 0x1c, 0x83, 0x55, 0x2b, 0xa8, 0x9b, 0xd9, 0x81, 0x92,
	0x96, 0x9f, 0xa7, 0x28, 0x89, 0xad, 0xb5, 0x75, 0x14, 0x32, 0x1e, 0x2d, 0x83, 0xe3, 0x1b, 0x52,
	0xba, 0x8f, 0x74, 0x6f, 0x48, 0x79, 0x5d, 0xd0, 0xcd, 0x84, 0x8d, 0x95, 0x90, 0x04, 0xda, 0xaf,
	0x2d, 0x28, 0xdf, 0xfd, 0x6a, 0x80, 0xe2, 0xd0, 0xf5, 0x03, 0x77, 0x60, 0x46, 0x9d, 0x73, 0x07,
	0xe4, 0xb5, 0x45, 0xdf, 0x82, 0xba, 0xe7, 0x7c, 0xfa, 0xd2, 0x19, 0xf9, 0x41, 0x7f, 0x78, 0x7e,
	0xfa, 0xbc, 0xdf, 0x23, 0xff, 0xd8, 0x94, 0x42, 0xf5, 0xbc, 0xdf, 0x73, 0xdc, 0x7e, 0x2f, 0xb8,
	0xf0, 0xdc, 0xe1, 0x19, 0xf9, 0xa5, 0xa4, 0x99, 0x06, 0x0b, 0xb4, 0x88, 0xf3, 0x59, 0x7f, 0xe4,
	0x93, 0x5f, 0x4b, 0xb4, 0x0a, 0xa5, 0xde, 0xc7, 0x81, 0xe3, 0x79, 0xae, 0x47, 0x7e, 0xaf, 0xd3,
	0x3a, 0x40, 0xef, 0xd4, 0x3f, 0xcd, 0x80, 0x3f, 0xea, 0x74, 0x17, 0x76, 0x46, 0x8e, 0x77, 0xee,
	0x78, 0x19, 0xf4, 0x67, 0x9d, 0xee, 0x80, 0xfd, 0x72, 0x38, 0x18, 0xba, 0x17, 0x43, 0xf2, 0xe3,
	0x9e, 0xb6, 0x1a, 0x3a, 0xfe, 0x85, 0xeb, 0x0d, 0x32, 0xc6, 0x4f, 0x7b, 0x26, 0xe9, 0xf3, 0x91,
	0xef, 0xbc, 0xc8, 0xa0, 0x9f, 0xf7, 0xba, 0x3f, 0xe4, 0xa0, 0xe6, 0x8b, 0x44, 0xaf, 0xc8, 0x08,
	0xe5, 0x82, 0x8f, 0x91, 0x7e, 0x01, 0xf6, 0x7a, 0x25, 0x9f, 0xde, 0x2e, 0xd3, 0xe6, 0x66, 0x37,
	0xdf, 0x7e, 0x78, 0xc7, 0x5a, 0x07, 0xdf, 0xfe, 0xf5, 0xf7, 0x77, 0xb9, 0x66, 0xeb, 0x69, 0x67,
	0x71, 0xdc, 0x31, 0x83, 0xbf, 0x7d, 0xa1, 0xa6, 0xa8, 0x4e, 0xac, 0x36, 0xfd, 0x12, 0xec, 0xd3,
	0x30, 0x34, 0xda, 0x8d, 0xfb, 0xda, 0x77, 0xaf, 0xd0, 0x03, 0xf2, 0x66, 0xe9, 0xde, 0x24, 0xcf,
	0xc2, 0x50, 0xcb, 0x8f, 0x01, 0x3c, 0x9c, 0x89, 0x05, 0x3e, 0xd2, 0xe1, 0x3d, 0xe3, 0xf0, 0x4e,
	0xab, 0xf1, 0x7f, 0x07, 0x69, 0x74, 0x4f, 0xac, 0xf6, 0x65, 0xd1, 0x3c, 0xa0, 0x1f, 0xfe, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xf4, 0x0e, 0x9a, 0x38, 0x85, 0x05, 0x00, 0x00,
}
