// Code generated by protoc-gen-go.
// source: protos/video/video.proto
// DO NOT EDIT!

/*
Package video is a generated protocol buffer package.

It is generated from these files:
	protos/video/video.proto

It has these top-level messages:
	RequestGetListVideoOne
	ResponseGetListVideoOne
	RequestGetListVideo
	ResponseGetListVideo
	RequestModifyListVideo
	RequestGetPromoteVideo
	ResponseGetPromoteVideo
	RequestModifyVideo
	ResponseGeneral
	RequestVideoID
	ResponseVideoDetail
	ResponseVideoDetailOne
	RequestVideoDetailOne
*/
package video

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_NOT_OK ErrorCode = 0
	ErrorCode_OK     ErrorCode = 200
	// client
	ErrorCode_REQUEST_INVALID ErrorCode = 1000
	// server response
	ErrorCode_VIDEOID_WRONG   ErrorCode = 1100
	ErrorCode_VIDEO_NOT_EXIST ErrorCode = 1101
	// server - Generic error for client
	ErrorCode_DB_ERROR     ErrorCode = 2000
	ErrorCode_DATA_ERROR   ErrorCode = 2001
	ErrorCode_SERVER_ERROR ErrorCode = 2002
	// general - unknown
	ErrorCode_UNKNOWN       ErrorCode = 3000
	ErrorCode_NETWORK_ERROR ErrorCode = 3001
	ErrorCode_SYSTEM_ERROR  ErrorCode = 3002
)

var ErrorCode_name = map[int32]string{
	0:    "NOT_OK",
	200:  "OK",
	1000: "REQUEST_INVALID",
	1100: "VIDEOID_WRONG",
	1101: "VIDEO_NOT_EXIST",
	2000: "DB_ERROR",
	2001: "DATA_ERROR",
	2002: "SERVER_ERROR",
	3000: "UNKNOWN",
	3001: "NETWORK_ERROR",
	3002: "SYSTEM_ERROR",
}
var ErrorCode_value = map[string]int32{
	"NOT_OK":          0,
	"OK":              200,
	"REQUEST_INVALID": 1000,
	"VIDEOID_WRONG":   1100,
	"VIDEO_NOT_EXIST": 1101,
	"DB_ERROR":        2000,
	"DATA_ERROR":      2001,
	"SERVER_ERROR":    2002,
	"UNKNOWN":         3000,
	"NETWORK_ERROR":   3001,
	"SYSTEM_ERROR":    3002,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListType int32

const (
	ListType_Comment               ListType = 0
	ListType_CommentWithLikeWeight ListType = 1
)

var ListType_name = map[int32]string{
	0: "Comment",
	1: "CommentWithLikeWeight",
}
var ListType_value = map[string]int32{
	"Comment":               0,
	"CommentWithLikeWeight": 1,
}

func (x ListType) String() string {
	return proto.EnumName(ListType_name, int32(x))
}
func (ListType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VideoStatus int32

const (
	VideoStatus_Exist   VideoStatus = 0
	VideoStatus_Private VideoStatus = 1
	VideoStatus_Public  VideoStatus = 2
	VideoStatus_Delete  VideoStatus = 3
	VideoStatus_NotExit VideoStatus = -1
)

var VideoStatus_name = map[int32]string{
	0:  "Exist",
	1:  "Private",
	2:  "Public",
	3:  "Delete",
	-1: "NotExit",
}
var VideoStatus_value = map[string]int32{
	"Exist":   0,
	"Private": 1,
	"Public":  2,
	"Delete":  3,
	"NotExit": -1,
}

func (x VideoStatus) String() string {
	return proto.EnumName(VideoStatus_name, int32(x))
}
func (VideoStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TimeInTopTrend int32

const (
	TimeInTopTrend_NotInTop TimeInTopTrend = 0
	TimeInTopTrend_InTop    TimeInTopTrend = 1
)

var TimeInTopTrend_name = map[int32]string{
	0: "NotInTop",
	1: "InTop",
}
var TimeInTopTrend_value = map[string]int32{
	"NotInTop": 0,
	"InTop":    1,
}

func (x TimeInTopTrend) String() string {
	return proto.EnumName(TimeInTopTrend_name, int32(x))
}
func (TimeInTopTrend) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type BlockTop int32

const (
	BlockTop_NotBlocked BlockTop = 0
	BlockTop_Blocked    BlockTop = 1
)

var BlockTop_name = map[int32]string{
	0: "NotBlocked",
	1: "Blocked",
}
var BlockTop_value = map[string]int32{
	"NotBlocked": 0,
	"Blocked":    1,
}

func (x BlockTop) String() string {
	return proto.EnumName(BlockTop_name, int32(x))
}
func (BlockTop) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RequestGetListVideoOne struct {
	RequestID string   `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	Listtype  ListType `protobuf:"varint,2,opt,name=listtype,enum=video.ListType" json:"listtype,omitempty"`
	Member    string   `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
}

func (m *RequestGetListVideoOne) Reset()                    { *m = RequestGetListVideoOne{} }
func (m *RequestGetListVideoOne) String() string            { return proto.CompactTextString(m) }
func (*RequestGetListVideoOne) ProtoMessage()               {}
func (*RequestGetListVideoOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseGetListVideoOne struct {
	Error       ErrorCode `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Result      string    `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *ResponseGetListVideoOne) Reset()                    { *m = ResponseGetListVideoOne{} }
func (m *ResponseGetListVideoOne) String() string            { return proto.CompactTextString(m) }
func (*ResponseGetListVideoOne) ProtoMessage()               {}
func (*ResponseGetListVideoOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestGetListVideo struct {
	RequestID string   `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	Listtype  ListType `protobuf:"varint,2,opt,name=listtype,enum=video.ListType" json:"listtype,omitempty"`
}

func (m *RequestGetListVideo) Reset()                    { *m = RequestGetListVideo{} }
func (m *RequestGetListVideo) String() string            { return proto.CompactTextString(m) }
func (*RequestGetListVideo) ProtoMessage()               {}
func (*RequestGetListVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ResponseGetListVideo struct {
	Error       ErrorCode         `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	List        map[string]string `protobuf:"bytes,3,rep,name=list" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResponseGetListVideo) Reset()                    { *m = ResponseGetListVideo{} }
func (m *ResponseGetListVideo) String() string            { return proto.CompactTextString(m) }
func (*ResponseGetListVideo) ProtoMessage()               {}
func (*ResponseGetListVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseGetListVideo) GetList() map[string]string {
	if m != nil {
		return m.List
	}
	return nil
}

type RequestModifyListVideo struct {
	RequestID   string            `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	Listtype    ListType          `protobuf:"varint,2,opt,name=listtype,enum=video.ListType" json:"listtype,omitempty"`
	MemberScore map[string]string `protobuf:"bytes,3,rep,name=member_score" json:"member_score,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestModifyListVideo) Reset()                    { *m = RequestModifyListVideo{} }
func (m *RequestModifyListVideo) String() string            { return proto.CompactTextString(m) }
func (*RequestModifyListVideo) ProtoMessage()               {}
func (*RequestModifyListVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestModifyListVideo) GetMemberScore() map[string]string {
	if m != nil {
		return m.MemberScore
	}
	return nil
}

type RequestGetPromoteVideo struct {
}

func (m *RequestGetPromoteVideo) Reset()                    { *m = RequestGetPromoteVideo{} }
func (m *RequestGetPromoteVideo) String() string            { return proto.CompactTextString(m) }
func (*RequestGetPromoteVideo) ProtoMessage()               {}
func (*RequestGetPromoteVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ResponseGetPromoteVideo struct {
	Error       ErrorCode `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	VideoID     string    `protobuf:"bytes,3,opt,name=videoID" json:"videoID,omitempty"`
}

func (m *ResponseGetPromoteVideo) Reset()                    { *m = ResponseGetPromoteVideo{} }
func (m *ResponseGetPromoteVideo) String() string            { return proto.CompactTextString(m) }
func (*ResponseGetPromoteVideo) ProtoMessage()               {}
func (*ResponseGetPromoteVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RequestModifyVideo struct {
	VideoID string            `protobuf:"bytes,1,opt,name=VideoID" json:"VideoID,omitempty"`
	Field   map[string]string `protobuf:"bytes,2,rep,name=field" json:"field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestModifyVideo) Reset()                    { *m = RequestModifyVideo{} }
func (m *RequestModifyVideo) String() string            { return proto.CompactTextString(m) }
func (*RequestModifyVideo) ProtoMessage()               {}
func (*RequestModifyVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestModifyVideo) GetField() map[string]string {
	if m != nil {
		return m.Field
	}
	return nil
}

type ResponseGeneral struct {
	Error       ErrorCode `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *ResponseGeneral) Reset()                    { *m = ResponseGeneral{} }
func (m *ResponseGeneral) String() string            { return proto.CompactTextString(m) }
func (*ResponseGeneral) ProtoMessage()               {}
func (*ResponseGeneral) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RequestVideoID struct {
	VideoID string `protobuf:"bytes,1,opt,name=VideoID" json:"VideoID,omitempty"`
}

func (m *RequestVideoID) Reset()                    { *m = RequestVideoID{} }
func (m *RequestVideoID) String() string            { return proto.CompactTextString(m) }
func (*RequestVideoID) ProtoMessage()               {}
func (*RequestVideoID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ResponseVideoDetail struct {
	Error       ErrorCode         `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	VideoDetail map[string]string `protobuf:"bytes,3,rep,name=video_detail" json:"video_detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResponseVideoDetail) Reset()                    { *m = ResponseVideoDetail{} }
func (m *ResponseVideoDetail) String() string            { return proto.CompactTextString(m) }
func (*ResponseVideoDetail) ProtoMessage()               {}
func (*ResponseVideoDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResponseVideoDetail) GetVideoDetail() map[string]string {
	if m != nil {
		return m.VideoDetail
	}
	return nil
}

type ResponseVideoDetailOne struct {
	Error       ErrorCode `protobuf:"varint,1,opt,name=error,enum=video.ErrorCode" json:"error,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Result      string    `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *ResponseVideoDetailOne) Reset()                    { *m = ResponseVideoDetailOne{} }
func (m *ResponseVideoDetailOne) String() string            { return proto.CompactTextString(m) }
func (*ResponseVideoDetailOne) ProtoMessage()               {}
func (*ResponseVideoDetailOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RequestVideoDetailOne struct {
	VideoID string `protobuf:"bytes,1,opt,name=videoID" json:"videoID,omitempty"`
	Field   string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
}

func (m *RequestVideoDetailOne) Reset()                    { *m = RequestVideoDetailOne{} }
func (m *RequestVideoDetailOne) String() string            { return proto.CompactTextString(m) }
func (*RequestVideoDetailOne) ProtoMessage()               {}
func (*RequestVideoDetailOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*RequestGetListVideoOne)(nil), "video.RequestGetListVideoOne")
	proto.RegisterType((*ResponseGetListVideoOne)(nil), "video.ResponseGetListVideoOne")
	proto.RegisterType((*RequestGetListVideo)(nil), "video.RequestGetListVideo")
	proto.RegisterType((*ResponseGetListVideo)(nil), "video.ResponseGetListVideo")
	proto.RegisterType((*RequestModifyListVideo)(nil), "video.RequestModifyListVideo")
	proto.RegisterType((*RequestGetPromoteVideo)(nil), "video.RequestGetPromoteVideo")
	proto.RegisterType((*ResponseGetPromoteVideo)(nil), "video.ResponseGetPromoteVideo")
	proto.RegisterType((*RequestModifyVideo)(nil), "video.RequestModifyVideo")
	proto.RegisterType((*ResponseGeneral)(nil), "video.ResponseGeneral")
	proto.RegisterType((*RequestVideoID)(nil), "video.RequestVideoID")
	proto.RegisterType((*ResponseVideoDetail)(nil), "video.ResponseVideoDetail")
	proto.RegisterType((*ResponseVideoDetailOne)(nil), "video.ResponseVideoDetailOne")
	proto.RegisterType((*RequestVideoDetailOne)(nil), "video.RequestVideoDetailOne")
	proto.RegisterEnum("video.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("video.ListType", ListType_name, ListType_value)
	proto.RegisterEnum("video.VideoStatus", VideoStatus_name, VideoStatus_value)
	proto.RegisterEnum("video.TimeInTopTrend", TimeInTopTrend_name, TimeInTopTrend_value)
	proto.RegisterEnum("video.BlockTop", BlockTop_name, BlockTop_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for VideoService service

type VideoServiceClient interface {
	GetVideoDetailOne(ctx context.Context, in *RequestVideoDetailOne, opts ...grpc.CallOption) (*ResponseVideoDetailOne, error)
	GetVideoDetail(ctx context.Context, in *RequestVideoID, opts ...grpc.CallOption) (*ResponseVideoDetail, error)
	// Delete video, delete field
	DeleteVideoDetail(ctx context.Context, in *RequestModifyVideo, opts ...grpc.CallOption) (*ResponseGeneral, error)
	// Set videoDetail, field, update field
	SetVideoDetail(ctx context.Context, in *RequestModifyVideo, opts ...grpc.CallOption) (*ResponseGeneral, error)
	// Video promote
	GetPromoteVideo(ctx context.Context, in *RequestGetPromoteVideo, opts ...grpc.CallOption) (*ResponseGetPromoteVideo, error)
	SetPromoteVideo(ctx context.Context, in *RequestVideoID, opts ...grpc.CallOption) (*ResponseGeneral, error)
	// Like, Comment of video
	GetListVideoOne(ctx context.Context, in *RequestGetListVideoOne, opts ...grpc.CallOption) (*ResponseGetListVideoOne, error)
	GetListVideo(ctx context.Context, in *RequestGetListVideo, opts ...grpc.CallOption) (*ResponseGetListVideo, error)
	AddListVideo(ctx context.Context, in *RequestModifyListVideo, opts ...grpc.CallOption) (*ResponseGeneral, error)
	RemoveListVideo(ctx context.Context, in *RequestModifyListVideo, opts ...grpc.CallOption) (*ResponseGeneral, error)
}

type videoServiceClient struct {
	cc *grpc.ClientConn
}

func NewVideoServiceClient(cc *grpc.ClientConn) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) GetVideoDetailOne(ctx context.Context, in *RequestVideoDetailOne, opts ...grpc.CallOption) (*ResponseVideoDetailOne, error) {
	out := new(ResponseVideoDetailOne)
	err := grpc.Invoke(ctx, "/video.VideoService/GetVideoDetailOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoDetail(ctx context.Context, in *RequestVideoID, opts ...grpc.CallOption) (*ResponseVideoDetail, error) {
	out := new(ResponseVideoDetail)
	err := grpc.Invoke(ctx, "/video.VideoService/GetVideoDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteVideoDetail(ctx context.Context, in *RequestModifyVideo, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.VideoService/DeleteVideoDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetVideoDetail(ctx context.Context, in *RequestModifyVideo, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.VideoService/SetVideoDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetPromoteVideo(ctx context.Context, in *RequestGetPromoteVideo, opts ...grpc.CallOption) (*ResponseGetPromoteVideo, error) {
	out := new(ResponseGetPromoteVideo)
	err := grpc.Invoke(ctx, "/video.VideoService/GetPromoteVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetPromoteVideo(ctx context.Context, in *RequestVideoID, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.VideoService/SetPromoteVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetListVideoOne(ctx context.Context, in *RequestGetListVideoOne, opts ...grpc.CallOption) (*ResponseGetListVideoOne, error) {
	out := new(ResponseGetListVideoOne)
	err := grpc.Invoke(ctx, "/video.VideoService/GetListVideoOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetListVideo(ctx context.Context, in *RequestGetListVideo, opts ...grpc.CallOption) (*ResponseGetListVideo, error) {
	out := new(ResponseGetListVideo)
	err := grpc.Invoke(ctx, "/video.VideoService/GetListVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) AddListVideo(ctx context.Context, in *RequestModifyListVideo, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.VideoService/AddListVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) RemoveListVideo(ctx context.Context, in *RequestModifyListVideo, opts ...grpc.CallOption) (*ResponseGeneral, error) {
	out := new(ResponseGeneral)
	err := grpc.Invoke(ctx, "/video.VideoService/RemoveListVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VideoService service

type VideoServiceServer interface {
	GetVideoDetailOne(context.Context, *RequestVideoDetailOne) (*ResponseVideoDetailOne, error)
	GetVideoDetail(context.Context, *RequestVideoID) (*ResponseVideoDetail, error)
	// Delete video, delete field
	DeleteVideoDetail(context.Context, *RequestModifyVideo) (*ResponseGeneral, error)
	// Set videoDetail, field, update field
	SetVideoDetail(context.Context, *RequestModifyVideo) (*ResponseGeneral, error)
	// Video promote
	GetPromoteVideo(context.Context, *RequestGetPromoteVideo) (*ResponseGetPromoteVideo, error)
	SetPromoteVideo(context.Context, *RequestVideoID) (*ResponseGeneral, error)
	// Like, Comment of video
	GetListVideoOne(context.Context, *RequestGetListVideoOne) (*ResponseGetListVideoOne, error)
	GetListVideo(context.Context, *RequestGetListVideo) (*ResponseGetListVideo, error)
	AddListVideo(context.Context, *RequestModifyListVideo) (*ResponseGeneral, error)
	RemoveListVideo(context.Context, *RequestModifyListVideo) (*ResponseGeneral, error)
}

func RegisterVideoServiceServer(s *grpc.Server, srv VideoServiceServer) {
	s.RegisterService(&_VideoService_serviceDesc, srv)
}

func _VideoService_GetVideoDetailOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVideoDetailOne)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoDetailOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/GetVideoDetailOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoDetailOne(ctx, req.(*RequestVideoDetailOne))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVideoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/GetVideoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoDetail(ctx, req.(*RequestVideoID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteVideoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteVideoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/DeleteVideoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteVideoDetail(ctx, req.(*RequestModifyVideo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetVideoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetVideoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/SetVideoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetVideoDetail(ctx, req.(*RequestModifyVideo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetPromoteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPromoteVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetPromoteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/GetPromoteVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetPromoteVideo(ctx, req.(*RequestGetPromoteVideo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetPromoteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVideoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetPromoteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/SetPromoteVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetPromoteVideo(ctx, req.(*RequestVideoID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetListVideoOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetListVideoOne)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetListVideoOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/GetListVideoOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetListVideoOne(ctx, req.(*RequestGetListVideoOne))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetListVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetListVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetListVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/GetListVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetListVideo(ctx, req.(*RequestGetListVideo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_AddListVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyListVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).AddListVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/AddListVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).AddListVideo(ctx, req.(*RequestModifyListVideo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_RemoveListVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestModifyListVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).RemoveListVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoService/RemoveListVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).RemoveListVideo(ctx, req.(*RequestModifyListVideo))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoDetailOne",
			Handler:    _VideoService_GetVideoDetailOne_Handler,
		},
		{
			MethodName: "GetVideoDetail",
			Handler:    _VideoService_GetVideoDetail_Handler,
		},
		{
			MethodName: "DeleteVideoDetail",
			Handler:    _VideoService_DeleteVideoDetail_Handler,
		},
		{
			MethodName: "SetVideoDetail",
			Handler:    _VideoService_SetVideoDetail_Handler,
		},
		{
			MethodName: "GetPromoteVideo",
			Handler:    _VideoService_GetPromoteVideo_Handler,
		},
		{
			MethodName: "SetPromoteVideo",
			Handler:    _VideoService_SetPromoteVideo_Handler,
		},
		{
			MethodName: "GetListVideoOne",
			Handler:    _VideoService_GetListVideoOne_Handler,
		},
		{
			MethodName: "GetListVideo",
			Handler:    _VideoService_GetListVideo_Handler,
		},
		{
			MethodName: "AddListVideo",
			Handler:    _VideoService_AddListVideo_Handler,
		},
		{
			MethodName: "RemoveListVideo",
			Handler:    _VideoService_RemoveListVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/video/video.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1041 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x53, 0x23, 0x45,
	0x14, 0xc7, 0x99, 0x20, 0x24, 0x79, 0x09, 0x99, 0xa1, 0x17, 0x36, 0x21, 0x82, 0xcb, 0x4e, 0x69,
	0x89, 0x59, 0x8b, 0x94, 0xd9, 0x83, 0x16, 0x37, 0x76, 0x67, 0xa4, 0x52, 0x40, 0x82, 0x93, 0x59,
	0xd0, 0x8b, 0x31, 0x30, 0x0f, 0x76, 0x24, 0x99, 0x8e, 0x33, 0x4d, 0x6a, 0xb9, 0x7a, 0xf2, 0xee,
	0xff, 0xe1, 0x59, 0xbd, 0x58, 0xe5, 0x89, 0x83, 0x56, 0xf9, 0xe3, 0x5f, 0xf0, 0xe0, 0x7f, 0xa1,
	0xd5, 0xdd, 0x43, 0x32, 0x93, 0x4c, 0xa0, 0x2a, 0xbb, 0x1c, 0xa8, 0xf4, 0xeb, 0x7e, 0xef, 0xf3,
	0xbe, 0xaf, 0xdf, 0x74, 0x37, 0x94, 0xfa, 0x3e, 0x65, 0x34, 0xa8, 0x0e, 0x5c, 0x07, 0xa9, 0xfc,
	0xbf, 0x2d, 0x4c, 0x64, 0x41, 0x0c, 0xca, 0xeb, 0x17, 0x94, 0x5e, 0x74, 0xb1, 0xda, 0xe9, 0xbb,
	0xd5, 0x8e, 0xe7, 0x51, 0xd6, 0x61, 0x2e, 0xf5, 0x02, 0xb9, 0x48, 0xff, 0x12, 0x1e, 0x5a, 0xf8,
	0xcd, 0x15, 0x06, 0x6c, 0x0f, 0xd9, 0x81, 0x1b, 0xb0, 0x63, 0xee, 0xd4, 0xf4, 0x90, 0x2c, 0x43,
	0xd6, 0x97, 0x33, 0x75, 0xa3, 0xa4, 0x6c, 0x2a, 0x5b, 0x59, 0xf2, 0x18, 0x32, 0x5d, 0x37, 0x60,
	0xec, 0xba, 0x8f, 0xa5, 0xd4, 0xa6, 0xb2, 0x55, 0xa8, 0xa9, 0xdb, 0x92, 0xc8, 0x3d, 0xed, 0xeb,
	0x3e, 0x92, 0x02, 0x2c, 0xf6, 0xb0, 0x77, 0x8a, 0x7e, 0x69, 0x9e, 0xbb, 0xe8, 0x6d, 0x28, 0x5a,
	0x18, 0xf4, 0xa9, 0x17, 0xe0, 0x38, 0xe0, 0x11, 0x2c, 0xa0, 0xef, 0x53, 0x5f, 0x04, 0x2f, 0xd4,
	0xb4, 0x30, 0x94, 0xc9, 0x6d, 0xcf, 0xa9, 0x83, 0xe4, 0x01, 0xe4, 0x1c, 0x0c, 0xce, 0x7c, 0xb7,
	0xcf, 0x33, 0x16, 0xc4, 0x2c, 0x07, 0xf8, 0x18, 0x5c, 0x75, 0x59, 0x08, 0xd8, 0x87, 0x07, 0x09,
	0x02, 0x66, 0xcb, 0x5e, 0xff, 0x41, 0x81, 0x95, 0xa4, 0x74, 0x67, 0xcc, 0xf5, 0x29, 0xbc, 0xc5,
	0x89, 0xa5, 0xf9, 0xcd, 0xf9, 0xad, 0x5c, 0xed, 0xbd, 0xd0, 0x29, 0x09, 0x20, 0x52, 0x30, 0x3d,
	0xe6, 0x5f, 0x97, 0x9f, 0x40, 0x76, 0x38, 0x20, 0x39, 0x98, 0xbf, 0xc4, 0xeb, 0x50, 0xc0, 0x12,
	0x2c, 0x0c, 0x3a, 0xdd, 0x2b, 0x99, 0x7d, 0x76, 0x27, 0xf5, 0x89, 0xa2, 0xdf, 0x28, 0xc3, 0xfd,
	0x3b, 0xa4, 0x8e, 0x7b, 0x7e, 0xfd, 0x9a, 0x15, 0x20, 0x06, 0xe4, 0xe5, 0xfe, 0xb5, 0x83, 0x33,
	0xea, 0x63, 0x98, 0xfa, 0xf6, 0x30, 0xf5, 0x24, 0xd4, 0xf6, 0xa1, 0xf0, 0x68, 0x71, 0x07, 0xa9,
	0xa1, 0x06, 0xda, 0xb8, 0xed, 0x5e, 0x29, 0xa5, 0x68, 0x27, 0x1e, 0xf9, 0xb4, 0x47, 0x19, 0x8a,
	0xf0, 0xfa, 0x57, 0xb1, 0x1e, 0x8a, 0x4e, 0xcd, 0xb8, 0x2f, 0x2a, 0xa4, 0xc5, 0xba, 0xba, 0x11,
	0x36, 0xd1, 0x77, 0x0a, 0x90, 0x98, 0x36, 0x19, 0x5d, 0x85, 0xf4, 0x71, 0xb8, 0x4e, 0x09, 0x37,
	0x74, 0xe1, 0xdc, 0xc5, 0xae, 0x53, 0x4a, 0x89, 0xb2, 0xbc, 0x9b, 0x54, 0x16, 0x59, 0x92, 0x4f,
	0xf9, 0x32, 0x59, 0x8c, 0x0f, 0x01, 0x46, 0xa3, 0x7b, 0xcb, 0xb0, 0x07, 0xea, 0x48, 0xac, 0x87,
	0x7e, 0xa7, 0x3b, 0x9b, 0x48, 0xfd, 0x31, 0x14, 0xc2, 0xbc, 0x42, 0x0d, 0x13, 0x72, 0xf4, 0x5f,
	0x15, 0xfe, 0xf1, 0x48, 0x98, 0x98, 0x31, 0x90, 0x75, 0xdc, 0x19, 0x81, 0x64, 0x17, 0xf2, 0x62,
	0x5d, 0xdb, 0x11, 0x51, 0xc2, 0xd6, 0x79, 0x32, 0xd6, 0xf5, 0x11, 0xce, 0x76, 0xe4, 0xf7, 0xb0,
	0x6f, 0xc6, 0x6d, 0xf7, 0x16, 0x4c, 0x9c, 0x60, 0x13, 0xb1, 0xdf, 0xdc, 0x01, 0xf3, 0x31, 0xac,
	0x46, 0xeb, 0x38, 0x0a, 0x1f, 0xe9, 0xa2, 0x61, 0x72, 0xb7, 0xdd, 0xa1, 0x6c, 0x65, 0x2b, 0x37,
	0x0a, 0x64, 0x47, 0x2c, 0x80, 0xc5, 0x46, 0xd3, 0x6e, 0x37, 0xf7, 0xb5, 0x39, 0x92, 0x86, 0x54,
	0x73, 0x5f, 0xbb, 0x51, 0xc8, 0x0a, 0xa8, 0x96, 0xf9, 0xd9, 0x0b, 0xb3, 0x65, 0xb7, 0xeb, 0x8d,
	0xe3, 0xdd, 0x83, 0xba, 0xa1, 0xfd, 0x9b, 0x26, 0x04, 0x96, 0x8e, 0xeb, 0x86, 0xd9, 0xac, 0x1b,
	0xed, 0x13, 0xab, 0xd9, 0xd8, 0xd3, 0x7e, 0xcb, 0xf0, 0x95, 0xc2, 0xd6, 0xe6, 0x41, 0xcc, 0xcf,
	0xeb, 0x2d, 0x5b, 0xfb, 0x3d, 0x43, 0x96, 0x20, 0x63, 0x3c, 0x6b, 0x9b, 0x96, 0xd5, 0xb4, 0xb4,
	0x3f, 0x54, 0xa2, 0x02, 0x18, 0xbb, 0xf6, 0x6e, 0x68, 0xf8, 0x53, 0x25, 0xcb, 0x90, 0x6f, 0x99,
	0xd6, 0xb1, 0x69, 0x85, 0xa6, 0xbf, 0x54, 0x92, 0x87, 0xf4, 0x8b, 0xc6, 0x7e, 0xa3, 0x79, 0xd2,
	0xd0, 0x7e, 0x2c, 0x72, 0x54, 0xc3, 0xb4, 0x4f, 0x9a, 0xd6, 0x7e, 0xb8, 0xe2, 0xa7, 0xa2, 0x70,
	0xfa, 0xa2, 0x65, 0x9b, 0x87, 0xa1, 0xe9, 0xe7, 0x62, 0xa5, 0x06, 0x99, 0xe1, 0x09, 0x91, 0x83,
	0xf4, 0x73, 0xda, 0xeb, 0xa1, 0xc7, 0xb4, 0x39, 0xb2, 0x06, 0xab, 0xe1, 0xe0, 0xc4, 0x65, 0x2f,
	0x0f, 0xdc, 0x4b, 0x3c, 0x41, 0xf7, 0xe2, 0x25, 0xd3, 0x94, 0x4a, 0x0b, 0x72, 0xa2, 0x60, 0x2d,
	0xd6, 0x61, 0x57, 0x01, 0xc9, 0xc2, 0x82, 0xf9, 0xca, 0x0d, 0xb8, 0x53, 0x0e, 0xd2, 0x47, 0xbe,
	0x3b, 0xe8, 0x30, 0xd4, 0x14, 0x5e, 0x97, 0xa3, 0xab, 0xd3, 0xae, 0x7b, 0xa6, 0xa5, 0xf8, 0x6f,
	0x03, 0xbb, 0xc8, 0x50, 0x9b, 0x27, 0x2b, 0x90, 0x6e, 0x50, 0x66, 0xbe, 0x72, 0x99, 0xf6, 0xdf,
	0xed, 0x9f, 0x52, 0xf9, 0x00, 0x0a, 0xb6, 0xdb, 0xc3, 0xba, 0x67, 0xd3, 0xbe, 0xed, 0xa3, 0xe7,
	0x90, 0x3c, 0x64, 0x1a, 0x94, 0x09, 0x83, 0x36, 0xc7, 0x29, 0xf2, 0xa7, 0x52, 0x79, 0x1f, 0x32,
	0xcf, 0xba, 0xf4, 0xec, 0xd2, 0xa6, 0x7d, 0x52, 0x00, 0x68, 0x50, 0x26, 0x86, 0xe8, 0xc8, 0x0c,
	0x6e, 0x07, 0x4a, 0xed, 0x97, 0x0c, 0xe4, 0x65, 0xa6, 0xe8, 0x0f, 0xdc, 0x33, 0x24, 0x0c, 0x96,
	0xf7, 0x70, 0x7c, 0xb7, 0xd7, 0xe3, 0xdf, 0x7a, 0x7c, 0xb6, 0xbc, 0x31, 0xbd, 0xcb, 0x9b, 0x1e,
	0xea, 0xfa, 0xb7, 0x7f, 0xff, 0xf3, 0x7d, 0x6a, 0x5d, 0x2f, 0x56, 0x07, 0x1f, 0x85, 0x37, 0xb5,
	0xfc, 0x48, 0xaa, 0x17, 0xc8, 0xa8, 0x87, 0x3b, 0x4a, 0x85, 0x38, 0x50, 0x88, 0x53, 0xc9, 0x6a,
	0x02, 0xb2, 0x6e, 0x94, 0xcb, 0xd3, 0x59, 0xfa, 0x23, 0x01, 0x5a, 0xd3, 0x57, 0x92, 0x40, 0x9c,
	0xf2, 0x35, 0x2c, 0xcb, 0x12, 0x47, 0x41, 0x6b, 0x53, 0xcf, 0xb1, 0xf2, 0xc3, 0x89, 0x4b, 0x4b,
	0x9c, 0x49, 0x77, 0x28, 0x72, 0x44, 0xf8, 0x50, 0x51, 0x2b, 0xae, 0x68, 0x06, 0xd0, 0x74, 0x45,
	0x81, 0x54, 0x44, 0x41, 0x1d, 0xbf, 0x15, 0x36, 0xe2, 0x98, 0xb1, 0xe9, 0xf2, 0x3b, 0x93, 0x17,
	0x71, 0xec, 0xbe, 0xd9, 0x10, 0xc8, 0xa2, 0xbe, 0x3a, 0x42, 0xf6, 0xe5, 0x3c, 0xaf, 0x22, 0x39,
	0x05, 0xb5, 0x35, 0x06, 0x9c, 0xb2, 0x53, 0xd3, 0x34, 0x6d, 0x0a, 0x40, 0x39, 0x09, 0x10, 0x8a,
	0xf2, 0x85, 0xa8, 0xd8, 0x73, 0x69, 0x52, 0x54, 0x74, 0x3a, 0x49, 0x54, 0x74, 0x3e, 0x89, 0xc9,
	0xdf, 0x02, 0x91, 0x06, 0x3c, 0x87, 0x7c, 0xec, 0xcd, 0x53, 0x9e, 0x0e, 0x2c, 0xbf, 0x7d, 0x07,
	0x6d, 0x58, 0x3f, 0x32, 0x89, 0x92, 0x6d, 0x91, 0xdf, 0x75, 0x9c, 0x11, 0x67, 0xe3, 0xce, 0xc7,
	0xc5, 0xd4, 0x22, 0x26, 0x52, 0x2e, 0xb1, 0xda, 0x71, 0x1c, 0xd9, 0xe8, 0xaa, 0x85, 0x3d, 0x3a,
	0xc0, 0xd7, 0x06, 0x25, 0x56, 0xee, 0x12, 0xab, 0xbe, 0x08, 0xbf, 0xa3, 0x54, 0x4e, 0x17, 0xc5,
	0x5b, 0xfa, 0xe9, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59, 0x31, 0xb0, 0xa3, 0x8c, 0x0b, 0x00,
	0x00,
}
